const
  LocalServersList: string =

'<servers>' +
  '<count>2</count>' +

  '<server1>' +
    '<name>Region52 Server</name>' +
    '<folder>Region52</folder>' +
    '<natives>versions\Natives</natives>' +
    '<minejar_folder>versions\Region52</minejar_folder>' +
    '<assets_folder>\assets</assets_folder>' +
    '<main_class>net.minecraft.launchwrapper.Launch</main_class>' +
    '<client_address>http://froggystyle.ru/Minecraft/Main.zip</client_address>' +
    '<assets_address>http://froggystyle.ru/Minecraft/Assets.zip</assets_address>' +
    '<game_version>1.7.5</game_version>' +
    '<asset_index>1.7.4</asset_index>' +
    '<tweak_class>--tweakClass optifine.OptiFineTweaker --tweakClass shadersmodcore.loading.SMCTweaker</tweak_class>' +
    '<primary_ip>127.0.0.1</primary_ip>' +
    '<secondary_ip>127.0.0.1</secondary_ip>' +
    '<serverport>65533</serverport>' +
    '<gameport>25565</gameport>' +
  '</server1>' +

  '<server2>' +
    '<name>Sandbox Server</name>' +
    '<folder>Sandbox</folder>' +
    '<natives>versions\Natives</natives>' +
    '<minejar_folder>versions\Region52</minejar_folder>' +
    '<assets_folder>\assets</assets_folder>' +
    '<main_class>net.minecraft.launchwrapper.Launch</main_class>' +
    '<client_address>http://froggystyle.ru/Minecraft/SecondServer/Main.zip</client_address>' +
    '<assets_address>http://froggystyle.ru/Minecraft/Assets.zip</assets_address>' +
    '<game_version>1.7.5</game_version>' +
    '<asset_index>1.7.4</asset_index>' +
    '<tweak_class>--tweakClass optifine.OptiFineTweaker --tweakClass shadersmodcore.loading.SMCTweaker</tweak_class>' +
    '<primary_ip>127.0.0.1</primary_ip>' +
    '<secondary_ip>127.0.0.1</secondary_ip>' +
    '<serverport>65533</serverport>' +
    '<gameport>25566</gameport>' +
  '</server2>' +

'</servers>';
